version: '2'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: poipond
      POSTGRES_USER: poipond
      POSTGRES_DB: poipond

  poipond:
    build: ./
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
    command: bash -c "rm -f /app/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
