development:
  adapter: mysql2
  encoding: utf8
  database: poipond_development
  pool: 5
  username: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

osm_development:
  adapter: postgresql
  encoding: unicode
  database: osm-nyc
  pool: 5
  username: randy
  password: 
  host: localhost
  port: 5432

test:
  adapter: mysql2
  encoding: utf8
  database: poipond_test
  pool: 5
  username: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
