development:
  adapter: mysql2
  encoding: utf8
  database: poipond_development
  pool: 5
  username: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock

test:
  adapter: mysql2
  encoding: utf8
  database: poipond_test
  pool: 5
  username: root
  host: localhost
  socket: /var/run/mysqld/mysqld.sock
