development:
  adapter: postgresql
  encoding: unicode
  database: poipond
  pool: 5
  username: poipond
  password: poipond
  host: db
  port: 5432

development_old:
  adapter: mysql2
  encoding: utf8
  database: poipond_development
  pool: 5
  username: root
  host: localhost

development_osm:
  adapter: postgresql
  encoding: unicode
  database: gis
  pool: 5
  username: gisuser
  password: password
  host: localhost
  port: 5432
